# Generated by Django 2.2.10 on 2020-06-03 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('operating_system', models.CharField(max_length=255)),
                ('ram', models.IntegerField()),
                ('pixels', models.IntegerField()),
                ('double_camera', models.BooleanField()),
                ('processor', models.CharField(max_length=255)),
                ('screen', models.CharField(max_length=255)),
                ('fm_radio', models.BooleanField()),
                ('misc', models.CharField(max_length=255)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phones.Vendor')),
            ],
        ),
    ]
