# Generated by Django 2.2.10 on 2020-06-03 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20200603_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samsung_phones',
            name='phone',
        ),
        migrations.AddField(
            model_name='phone',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phones.Vendor'),
        ),
        migrations.AddField(
            model_name='samsung_phones',
            name='sams_field',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Apple_Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appl_field', models.CharField(max_length=255)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phones.Vendor')),
            ],
        ),
    ]
