# Generated by Django 2.2.10 on 2020-06-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200605_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletags',
            options={'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематики статьи'},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', through='articles.ArticleTags', to='articles.Tag'),
        ),
        migrations.AlterField(
            model_name='articletags',
            name='is_main',
            field=models.BooleanField(verbose_name='Основная'),
        ),
    ]
