# Generated by Django 3.0.7 on 2020-06-20 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('istore', '0002_merchandise_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT,
                                    to='istore.CategoryGroup'),
        ),
    ]
