# Generated by Django 3.0.7 on 2020-06-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('istore', '0004_auto_20200620_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='slug',
            field=models.SlugField(default=None, null=True),
            preserve_default=False,
        ),
    ]
