# Generated by Django 3.0.7 on 2020-06-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('istore', '0007_auto_20200621_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(null=True, related_name='orders', through='istore.OrderDetails',
                                         to='istore.Merchandise'),
        ),
    ]
